apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    app: apt-jmeter
  name: apt-jmeter-job
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      labels:
        app: apt-jmeter
      name: apt-jmeter
    spec:
      parallelism: 1
      completions: 1
      template:
        metadata:
          name: apt-jmeter
          labels:
            testplan: apt-jmx
        spec:
          containers:
          - name: jmeter
            image: jmeter-image:latest
            resources:
              requests:
              # commented out on Code Ready Containers 
              #  cpu: '500m'
              #  memory: 1Gi
            env:
              - name: J_PAIN_TEMPLATE_LOCATION
                value: /opt/jmeter/tests/pain_template.xml
              - name: J_PAIN_CSV_LOCATION
                value: /opt/jmeter/tests/pain_samples.csv
              - name: J_sample_variables
                value: "MSG_ID,JMS_TIMESTAMP"
              - name: J_BROKER
                value: messaging
              - name: J_PORT
                value: "5671"
              - name: RESULT_SUB_DIR
                value: ${RESULT_SUB_DIR}
              - name: PLAN_SUB_DIR
                value: ${PLAN_SUB_DIR}
              - name: CALLBACK_URL
                value: ${CALLBACK_URL}
            volumeMounts:
              - mountPath: /opt/jmeter/tests
                name: tests
              - mountPath: /opt/jmeter/results
                name: results
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          restartPolicy: OnFailure
          volumes:
            - name: "tests"
              persistentVolumeClaim:
                claimName: ${JMX_PVC}
parameters:
  - description: Namespace/project the job is created in
    name: NAMESPACE
    value: perftest
  - description: Name of the persistent volume claim to use for storing the test(s) results
    name: JTL_PVC
    value: apt-jmeter
  - description: Name of the persistent volume claim to use for finding JMX testplans
    name: JMX_PVC
    value: jenkins
  - description: Name of the subdirectory where test results are to be stored 
    name: RESULT_SUB_DIR
  - description: Name of the subdirectory where test plans have been downloaded by Jenkins
    name: PLAN_SUB_DIR
  - description: Url for notification of test completion 
    name: CALLBACK_URL
